apiVersion: apps/v1
kind: Deployment
metadata:
  name: deskew-app-deployment
  labels:
    app: deskew-app
spec:
  selector:
    matchLabels:
      app: deskew-app
  replicas: 3
  template:
    metadata:
      labels:
        app: deskew-app
    spec:
      containers:
      - name: deskew-kube-container
        image: ck1998/deskew_app_image:1.0.0
        env:
        - name: PORT
          value: "5000"
        ports:
        - containerPort: 5000
