name: Build

on:
  push:
    branches: [ main ]

jobs:
  
  build:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      
      - name: docker login
        env: 
          DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER_NAME -p $DOCKER_PASSWORD
        
      - name: docker build deskew image
        env: 
          DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker build ./deskewImageAppProject -t $DOCKER_USER_NAME/deskew_app_image:1.0.0
        
      - name: docker push
        env: 
          DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
        run: docker push $DOCKER_USER_NAME/deskew_app_image:1.0.0
      
      - name: heroku login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: remove previous app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ secrets.APP_NAME }}
        run: heroku apps:destroy $APP_NAME --confirm $APP_NAME
      
      - name: create app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ secrets.APP_NAME }}
        run: heroku create $APP_NAME
        
      - name: push app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ secrets.APP_NAME }}
        working-directory: ./deskewImageAppProject
        run: heroku container:push web -a $APP_NAME
        
      - name: release app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ secrets.APP_NAME }}
        run: heroku container:release web -a $APP_NAME
