name: Build-CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: docker login
        env: 
          DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER_NAME -p $DOCKER_PASSWORD
        
      - name: docker build deskew image
        env: 
          DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker build ./deskewImageAppProject -t $DOCKER_USER_NAME/deskew_app_image:1.0.0
        
      - name: docker push
        env: 
          DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
        run: docker push $DOCKER_USER_NAME/deskew_app_image:1.0.0
      
      - name: heroku Build, Push, Release
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_MAIL }}
          heroku_app_name: ${{ secrets.APP_NAME }}
          dockerfile_directory: ./deskewImageAppProject
          docker_options: "--no-cache"
      
      
      
