name: DockerCI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build deskew image
        run: docker build ./deskewImageAppProject -t ck1998/deskew:1.0.0
